apiVersion: v1
entries:
  postgresql:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 11.10.0
    created: "2021-07-07T08:37:06.8442603+02:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 1.x.x
    description: Chart for PostgreSQL, an object-relational database management system (ORDBMS) with an emphasis on extensibility and on standards-compliance.
    digest: eebe8f456cf98d5927a35666d1d899174dc4d3e09f26788033f761527bc90749
    home: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-110x117.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: postgresql
    sources:
    - https://github.com/bitnami/bitnami-docker-postgresql
    - https://www.postgresql.org/
    urls:
    - charts/postgresql-10.1.1.tgz
    version: 10.1.1
  redis:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 6.0.11
    created: "2021-07-07T08:37:06.8472601+02:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: Open source, advanced key-value store. It is often referred to as a data structure server since keys can contain strings, hashes, lists, sets and sorted sets.
    digest: 2d70861d16fc410ed6d6c818b97f7b0d519031147e5c7b42c5691d4c38742c44
    home: https://github.com/bitnami/charts/tree/master/bitnami/redis
    icon: https://bitnami.com/assets/stacks/redis/img/redis-stack-220x234.png
    keywords:
    - redis
    - keyvalue
    - database
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: redis
    sources:
    - https://github.com/bitnami/bitnami-docker-redis
    - http://redis.io/
    urls:
    - charts/redis-12.7.7.tgz
    version: 12.7.7
  waardepapieren-balie:
  - annotations:
      artifacthub.io/containsSecurityUpdates: "true"
    apiVersion: v2
    appVersion: V1.0
    created: "2021-07-07T08:37:06.8392598+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.1.1
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 12.7.7
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface beschikbaar.
    digest: bc4a9c6bba5caa0420f805db3f7ed7309c4bb1c81141f1ee953cdd98f5890e37
    home: https://www.conduction.nl
    icon: https://conductionnl.github.io/images/conduction_avatar_blue_on_transparant.svg
    keywords:
    - commonground
    - haven
    - nlx
    - component
    maintainers:
    - email: ruben@conduction.nl
      name: Ruben van der Linde
    - email: info@conduction.nl
      name: Conduction
    name: waardepapieren-balie
    sources:
    - https://commonground.conduction.nl/
    - https://www.commonground.nl/
    urls:
    - waardepapieren-balie-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v1
    appVersion: V1.0
    created: "2021-07-07T08:37:06.8322587+02:00"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface beschikbaar.
    digest: b33c06d12956dd53dfa432e5eacd568ec8f54f9e194cdca9bb8e167619a861cd
    home: https://www.conduction.nl
    icon: https://conductionnl.github.io/images/conduction_avatar_blue_on_transparant.svg
    keywords:
    - commonground
    - haven
    - nlx
    - component
    maintainers:
    - email: ruben@conduction.nl
      name: Ruben van der Linde
    - email: info@conduction.nl
      name: Conduction
    name: waardepapieren-balie
    sources:
    - https://commonground.conduction.nl/
    - https://www.commonground.nl/
    urls:
    - waardepapieren-balie-0.1.0.tgz
    version: 0.1.0
generated: "2021-07-07T08:37:06.8232596+02:00"
